
FROM docker.io/centos:7
MAINTAINER Denis Arnaud <denis.arnaud_fedora@m4x.org>

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum -y clean all
RUN yum -y update

CMD ["/bin/bash"]

